//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.PhieuDVs = new HashSet<PhieuDV>();
            this.ToaThuocs = new HashSet<ToaThuoc>();
        }
    
        public int id { get; set; }
        public System.DateTime NgayKham { get; set; }
        public int TienKham { get; set; }
        public int TienDV { get; set; }
        public Nullable<int> TienThuoc { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int idBN { get; set; }
        public int idPK { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual PhieuKham PhieuKham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDV> PhieuDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToaThuoc> ToaThuocs { get; set; }
    }
}
