//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietTTs = new HashSet<ChiTietTT>();
            this.CTDVs = new HashSet<CTDV>();
        }
    
        public int id { get; set; }
        public System.DateTime NgayKham { get; set; }
        public int TienKham { get; set; }
        public int TienDV { get; set; }
        public Nullable<int> TienThuoc { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int idPK { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTT> ChiTietTTs { get; set; }
        public virtual PhieuKham PhieuKham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDV> CTDVs { get; set; }
    }
}
