//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLPMEntities : DbContext
    {
        public QLPMEntities()
            : base("name=QLPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<ChiTietTT> ChiTietTTs { get; set; }
        public virtual DbSet<CTDV> CTDVs { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<PhieuKham> PhieuKhams { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_GetAccountByUsername(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetAccountByUsername", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetID(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetID", nameParameter);
        }
    
        public virtual ObjectResult<SP_SearchBN_Result> SP_SearchBN(string ten, Nullable<int> id)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchBN_Result>("SP_SearchBN", tenParameter, idParameter);
        }
    
        [DbFunction("QLPMEntities", "FN_DoanhThu_Thuoc")]
        public virtual IQueryable<FN_DoanhThu_Thuoc_Result> FN_DoanhThu_Thuoc(Nullable<System.DateTime> ngaytruoc, Nullable<System.DateTime> ngaysau)
        {
            var ngaytruocParameter = ngaytruoc.HasValue ?
                new ObjectParameter("ngaytruoc", ngaytruoc) :
                new ObjectParameter("ngaytruoc", typeof(System.DateTime));
    
            var ngaysauParameter = ngaysau.HasValue ?
                new ObjectParameter("ngaysau", ngaysau) :
                new ObjectParameter("ngaysau", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_DoanhThu_Thuoc_Result>("[QLPMEntities].[FN_DoanhThu_Thuoc](@ngaytruoc, @ngaysau)", ngaytruocParameter, ngaysauParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DEM(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DEM", thangParameter);
        }
    }
}
