//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDV()
        {
            this.CTDVs = new HashSet<CTDV>();
        }
    
        public int id { get; set; }
        public System.DateTime NgayKhamDV { get; set; }
        public int idHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDV> CTDVs { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
